name: CI Static Tests

on:
  push:
jobs:
  static:
    name: "Static CI Tests"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-python@v2

      - uses: pre-commit/action@v2.0.3
