name: CI Application Tests

on:
  push:
jobs:
  built_unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name : checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-go@v3.3.0
        with:
          go-version: '1.16'

      - name: run tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic -json  ./... > test.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1

      - name: annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: test.json

  build:
    name: "Application CI Tests"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - uses: ynniss/golang-security-action@v0.1.3

      - uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1

      - uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
