name: CI Application Tests

on:
  push:
jobs:
  build:
    name: "Application CI Tests"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - uses: ynniss/golang-security-action@v0.1.3

      - uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.34

      - uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
