name: Release Deliver to Master

on:
  release:
    types: [published]

jobs:
  publish_docs:
    name: "Publish the the Release to Master"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Merge Tag -> Master
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ github.event.ref }}
          target_branch: main
          github_token: ${{ github.token }}
